#!/bin/bash
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y
apt-get autoremove -y
apt-get install apt-utils build-essential -y
apt-get install git -y
apt-get install checkinstall libpcre3 libpcre3-dev zlib1g zlib1g-dbg libxml2 zlib1g-dev -y
apt-get install -y unzip
apt-get install -y libicu-dev libcurl4-gnutls-dev libtool
apt-get install -y libmozjs-24-dev
apt-get install -y libmozjs-24-bin; sudo ln -sf /usr/bin/js24 /usr/bin/js
apt-get install openssl libssl-dev libperl-dev libexpat-dev -y
apt-get install mercurial meld -y
apt-get install libxslt-dev -y
apt-get install libgd2-xpm -y
apt-get install libgd2-xpm-dev -y
apt-get install libgeoip-dev -y
apt-get install libssl libssl-dev -y
apt-get install dh-autoreconf -y
apt-get install -y software-properties-common
apt-get install -y python-software-properties
apt-get install -y libcairo2 libcairo2-dev
apt-get install -y python-dev
sudo add-apt-repository ppa:maxmind/ppa -y
apt-get install aptitude -y
aptitude update -y
aptitude upgrade -y
aptitude install libmaxminddb0 libmaxminddb-dev mmdb-bin -y
apt-get install libmysqlclient-dev -y
apt-get install libmariadbclient-dev -y
apt-get install g++ flex bison curl doxygen libyajl-dev libgeoip-dev libtool dh-autoreconf libcurl4-gnutls-dev libxml2 libpcre++-dev libxml2-dev -y
# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
# GET NGINX PLUS.
cd /; wget http://cdn.systemroot.co/nginx/plus.zip; unzip plus.zip; rm -Rf plus.zip
# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
# FIX.
# ====================================================================================
chmod +x /usr/sbin/nginx
chmod +x /etc/init.d/nginx
chmod +x /usr/sbin/nginx-debug
chmod +x /etc/init.d/nginx-debug
mkdir -p /var/log/nginx/
mkdir -p /etc/nginx/live/
mkdir -p /hostdata/
ln -s /etc/nginx/ /nginx
touch /var/log/nginx/error.log
touch /var/log/nginx/access.log

# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
# RE'CONF.
# ====================================================================================
cd /nginx; rm -Rf nginx.conf; wget https://raw.githubusercontent.com/theraw/my-nginx/master/nginx-plus/static/nginx.conf; clear
# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
# BUILD D.MODS.
# ====================================================================================
mkdir /raw; cd /raw; wget https://raw.githubusercontent.com/theraw/my-nginx/master/nginx-plus/dynamic-mods
chmod +x /raw/dynamic-mods
./dynamic-mods; cd ~/; rm -Rf /raw
# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ====================================================================================
# UP.
# ====================================================================================
fpm restart
service nginx restart
# ====================================================================================
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
