#!/bin/bash
apt-get install software-properties-common -y
apt-get install python-software-properties -y
sudo add-apt-repository ppa:ondrej/php -y
apt-get update; apt-get upgrade -y
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
apt-get update; apt-get upgrade -y

apt-get install php5.6-fpm -y
apt-get install php5.6 php5.6-common php5.6-cgi php5.6-cli php5.6-dev php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-ldap php5.6-mysql php5.6-pgsql php5.6-recode php5.6-tidy php5.6-json php5.6-bz2 php5.6-mcrypt php5.6-readline php5.6-interbase php5.6-xmlrpc php5.6-gmp php5.6-xsl php5.6-mbstring php5.6-soap php5.6-xml php5.6-zip -y

cd /bin; curl -s -O https://raw.githubusercontent.com/theraw/dope-manager/master/helper/fpm6
chmod +x /bin/fpm6
cd /etc/php/5.6/fpm/
rm -Rf php.ini
wget https://raw.githubusercontent.com/theraw/dope-manager/master/php/5.6/php.ini
cd /etc/php/5.6/fpm/pool.d/; rm -Rf www.conf
wget https://raw.githubusercontent.com/theraw/dope-manager/master/php/5.6/www.conf
fpm6 restart
